(load "C:/sicp/2_2.scm")

(define (make-rectangle l w)
        (cons l w)
)
(define (l-rectangle r)
        (car r)
)
(define (w-rectangle r)
        (cdr r)
)

(define (length-of-rectangle r)
        (let ((l (l-rectangle r)))
             (let ((start (start-segment l)) (end (end-segment l)))
                  (- (x-point end) (x-point start))
             )
        )
)

(define (width-of-rectangle r)
        (let ((w (w-rectangle r)))
             (let ((start (start-segment w)) (end (end-segment w)))
                  (- (y-point end) (y-point start))
              )
        )
)

(define (perimeter-rectangle r)
        (let ((l (length-of-rectangle r))
              (w (width-of-rectangle r))
             )
             (* 2 (+ l w))
        )
)
(define (area-rectangle r)
        (* (length-of-rectangle r) (width-of-rectangle r))
)

(define (print-rectangle r)
        (display "(")
        (print-segment (l-rectangle r))
        (display ",")
        (print-segment (w-rectangle r))
        (display ")")
)
