(define (cont-frac N D k)
        (define (cf i)
                (if (= k i)
                    (/ (N k) (D k))
                    (/ (N i) (+ (D i) (cf (+ i 1))))
                )
        )
        (cf 1)
)

(define (e k)
        (define (N i) 1)
        (define (D i)
                (if (= 2 (remainder i 4)) (* 2 (/ (+ i 2) 4)) 1)
        )
        (+ 2.0 (cont-frac N D k))
)
