(define (sum term a next b)
        (if (> a b)
          0
          (+ (term a) (sum term (next a) next b))
        )
)
;a**3 + (a+1)**3+...+b**3
(define (inc n) (+ n 1))
(define (cube a) (* a a a))
(define (sum-cubes a b)
        (sum cube a inc b)
)
;a+(a=1)+...+b
(define (identity x) x)
(define (sum-integers a b)
        (sum identity a inc b)
)
;1/(1*3)+1/(5*7)+1/(9*11)
(define (pi-sum a b)
    (define (pi-term x)
            (/ 1.0 (* x (+ x 2)))
    )
    (define (pi-next x)
            (+ x 4)
    )
    (sum pi-term a pi-next b)
)
;定积分
(define (integral f a b dx)
        (define (add-dx x) (+ x dx))
        (* (sum f (+ a (/ dx 2.0)) add-dx b) dx)
)
