DROP DATABASE IF EXISTS test;
CREATE DATABASE test;
USE test;
DROP TABLE IF EXISTS user;
CREATE TABLE IF NOT EXISTS user(
  id INT PRIMARY KEY AUTO_INCREMENT,
  account VARCHAR(10) NOT NULL UNIQUE,
  name VARCHAR(10)
)ENGINE=InnoDB charset=utf8;
